[update]
tasks = ["interfaces", "normalize"]

[update.interfaces]
paths = ["Application/Resources"]
defaultToBase = false
ignoreEmptyStrings = false
unstripped = false

[update.normalize]
paths = ["Application/Resources"]
sourceLocale = "Base"
harmonizeWithSource = true
sortByKeys = true

[lint]
paths = ["Application/Resources"]
duplicateKeys = true
emptyValues = true
