include:
  - projectDependencies.yml
  - ../XcodeGen/target-templates.yml
name: Example Project
options:
  settingPresets: none
  groupOrdering:
    - pattern: '^Application$'
      order: [Sources, Resources]
  groupSortPosition: top
  xcodeVersion: "1240"
configs:
  Development-Debug: debug
  Development-Release: release
  Test-Debug: debug
  Test-Release: release
  Staging-Debug: debug
  Staging-Release: release
  Production-Debug: debug
  Production-Release: release
configFiles:
  Development-Debug: Supporting Files/Settings (Debug).xcconfig
  Development-Release: Supporting Files/Settings (Release).xcconfig
  Test-Debug: Supporting Files/Settings (Debug).xcconfig
  Test-Release: Supporting Files/Settings (Release).xcconfig
  Staging-Debug: Supporting Files/Settings (Debug).xcconfig
  Staging-Release: Supporting Files/Settings (Release).xcconfig
  Production-Debug: Supporting Files/Settings (Debug).xcconfig
  Production-Release: Supporting Files/Settings (Release).xcconfig
targets:
  Example Project:
    templates:
      - iOS App
    sources:
      - path: Application
        excludes:
          - "**/.gitkeep"
      - path: Rome
        optional: true
        excludes:
          - "*.framework"
          - "*.xcframework"
    settings:
      base:
        DEVELOPMENT_TEAM: 3JQPC5UP5E
        INFOPLIST_FILE: Application/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Application/Resources/Entitlements.entitlements
        PRODUCT_NAME: $(TARGET_NAME)
        SWIFT_VERSION: 5.0
      configs:
        Development:
          PRODUCT_BUNDLE_IDENTIFIER: be.appwise.Example-Project-Development
        Test:
          PRODUCT_BUNDLE_IDENTIFIER: be.appwise.Example-Project-Test
        Staging:
          PRODUCT_BUNDLE_IDENTIFIER: be.appwise.Example-Project-Staging
        Production:
          PRODUCT_BUNDLE_IDENTIFIER: be.appwise.Example-Project
    scheme:
      configVariants:
        - Development
        - Test
        - Staging
        - Production
