include:
  - projectDependencies.yml
  - Pods/AppwiseCore/XcodeGen/target-templates.yml
name: Example Project
options:
  createIntermediateGroups: true
  settingPresets: none
  groupOrdering:
    - pattern: '.*'
      order: [Sources, Resources]
  groupSortPosition: top
  xcodeVersion: "14.3"
configs:
  Development Debug: debug
  Development Release: release
  Test Debug: debug
  Test Release: release
  Staging Debug: debug
  Staging Release: release
  Production Debug: debug
  Production Release: release
configFiles:
  Development Debug: Supporting Files/Settings (Debug).xcconfig
  Development Release: Supporting Files/Settings (Release).xcconfig
  Test Debug: Supporting Files/Settings (Debug).xcconfig
  Test Release: Supporting Files/Settings (Release).xcconfig
  Staging Debug: Supporting Files/Settings (Debug).xcconfig
  Staging Release: Supporting Files/Settings (Release).xcconfig
  Production Debug: Supporting Files/Settings (Debug).xcconfig
  Production Release: Supporting Files/Settings (Release).xcconfig
settings:
  settings:
    base:
      DEVELOPMENT_TEAM: XXXXXXXXXX
  configs:
    Development:
      APP_BUNDLE_IDENTIFIER: be.appwise.Example-Project-Development
    Test:
      APP_BUNDLE_IDENTIFIER: be.appwise.Example-Project-Test
    Staging:
      APP_BUNDLE_IDENTIFIER: be.appwise.Example-Project-Staging
    Production:
      APP_BUNDLE_IDENTIFIER: be.appwise.Example-Project
targetTemplates:
  Common:
    sources:
      - path: ${target_dir}
        excludes:
          - "**/.gitkeep"
      - path: Rome
        optional: true
        excludes:
          - "*.framework"
          - "*.xcframework"
          - "*.a"
targets:
  Example Project:
    templates:
      - iOS App
      - Common
    templateAttributes:
      target_dir: Application
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(APP_BUNDLE_IDENTIFIER)
    scheme:
      configVariants:
        - Development
        - Test
        - Staging
        - Production
      testTargets:
        - name: Tests
          parallelizable: true
          randomExecutionOrder: true
        - name: UITests
          parallelizable: true
          randomExecutionOrder: true
    entitlements:
      path: ${target_dir}/Resources/Entitlements.entitlements
  Tests:
    type: bundle.unit-test
    platform: iOS
    templates:
      - Common
    templateAttributes:
      target_dir: Tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(APP_BUNDLE_IDENTIFIER).Tests
        PRODUCT_NAME: $(TARGET_NAME)
  UITests:
    type: bundle.ui-testing
    platform: iOS
    templates:
      - Common
    templateAttributes:
      target_dir: UITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(APP_BUNDLE_IDENTIFIER).UITests
        PRODUCT_NAME: $(TARGET_NAME)