fastlane_version '2.137.0'
default_platform :ios

platform :ios do
  desc 'Submit a new Development Build to Apple TestFlight'
  lane :development do
    scheme = CredentialsManager::AppfileConfig.try_fetch_value(:scheme)
    archiveAndUpload(scheme: scheme)
  end

  desc 'Submit a new Development Build to Apple TestFlight'
  lane :staging do
    scheme = CredentialsManager::AppfileConfig.try_fetch_value(:scheme)
    archiveAndUpload(scheme: scheme)
  end

  desc 'Submit a new Production Build to Apple TestFlight'
  lane :production do
    scheme = CredentialsManager::AppfileConfig.try_fetch_value(:scheme)
    archiveAndUpload(scheme: scheme)
  end

  desc 'Deploy a new version to the App Store'
  lane :release do
    version_number = get_version_number
    sentry_project = CredentialsManager::AppfileConfig.try_fetch_value(:sentry_project)

    upload_to_app_store(
      submit_for_review: true,
      skip_binary_upload: true,
      force: true
    )
    sentry_finalize_release(
      version: "#{sentry_project}@#{version_number}"
    )
  end

  desc 'Download dSYMs from iTC and upload them to Sentry'
  lane :refresh_dsyms do
    identifiers = CredentialsManager::AppfileConfig.try_fetch_value(:identifiers)

    identifiers.each do |identifier|
      syncDsyms(identifier: identifier)
    end
  end

  desc "Extracts localizations from the xcode project"
  lane :export_translations do
    require './../../Scripts/fastlane_translations.rb'
    export_translations_and_strip_ignored()
  end

  desc "Imports localizations into the xcode project"
  lane :import_translations do
    require './../../Scripts/fastlane_translations.rb'
    import_translations()
  end

  private_lane :archiveAndUpload do |options|
    scheme = options[:scheme]
    version_number = get_version_number
    sentry_project = CredentialsManager::AppfileConfig.try_fetch_value(:sentry_project)

    get_provisioning_profile(
      output_path: 'fastlane/build'
    )
    build_ios_app(
      scheme: scheme,
      include_bitcode: true,
      output_directory: 'fastlane/build',
      output_name: "#{scheme}.ipa",
      silent: true
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
    sentry_create_release(
      version: "#{sentry_project}@#{version_number}"
    )
  end

  private_lane :syncDsyms do |options|
    identifier = options[:identifier]

    download_dsyms(
      app_identifier: identifier,
      output_directory: 'fastlane/build'
    )
    sentry_upload_dsym
    clean_build_artifacts
    lane_context[SharedValues::DSYM_PATHS] = []
  end
end
