output_directory('./fastlane/screenshots')
derived_data_path('./fastlane/build/derived_data')

clear_previous_screenshots(true)
localize_simulator(true)
override_status_bar(true)
test_without_building(true)
suppress_xcode_output(true)
skip_open_summary(true)

devices([
  "iPhone 8 Plus",
  "iPhone 14 Pro",
])

languages([
  "en-US",
  "nl-BE"
])